# Generated by Django 4.0.4 on 2022-07-20 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('post_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Related_Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Nomi')),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='post/')),
                ('published_date_time', models.DateTimeField(null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('video', models.FileField(upload_to='post_videos/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='base.category')),
                ('related_regions', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='base.related_regions')),
            ],
        ),
    ]
